# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

lane :distribute do

    gradle(
         task: 'assemble',
         build_type: 'Debug'
    )

   // gradle(   tasks: ["getCommitMessage"])

    firebase_app_distribution(
            app: "1:485636102691:android:5b0b9497e137be1f",
            groups: "testers",
            release_notes_file: "release-notes.txt",
            service_credentials_file: "distribution-key.json"
    )

end

lane :beta do
  gradle(task: 'clean')
  gradle(
    task: 'assemble',
    build_type: 'release'
  )
  upload_to_play_store(
    package_name: 'com.goda.npmoa',
    track: 'beta',
    apk: 'app/build/outputs/apk/release/app-release.apk',
    skip_upload_metadata: 'true',
    skip_upload_images: 'true',
    skip_upload_screenshots: 'true'
  )
end
